"""emp dept junction edit

Revision ID: a97f933d9e86
Revises: 1f0ec87444c1
Create Date: 2026-06-01 11:40:16.596919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97f933d9e86'
down_revision: Union[str, Sequence[str], None] = '1f0ec87444c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("employee_dept") as batch_op:
        batch_op.drop_index(op.f("ix_employee_dept_id"))
        batch_op.drop_column("id")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
