"""employee roles update

Revision ID: ae851f5533a9
Revises: a97f933d9e86
Create Date: 2026-06-01 14:11:43.012776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae851f5533a9'
down_revision: Union[str, Sequence[str], None] = 'a97f933d9e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ROLE_ENUM= sa.Enum('UI', 'UX', 'Developer', 'HR', name='employeerole')
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_dept', 'updated_at')
    op.drop_column('employee_dept', 'deleted_at')
    op.drop_column('employee_dept', 'created_at')

    _ROLE_ENUM.create(op.get_bind(), checkfirst=True)
    op.add_column('employees', sa.Column('role',_ROLE_ENUM, server_default='Developer', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'role')
    op.add_column('employee_dept', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('employee_dept', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('employee_dept', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
